### ISSUE TITLE
http_parse_basic leaves password in memory when freeing buffer

### ISSUE THREAD

**Issue by ailrst** [versat/cntlm#105]
https://github.com/versat/cntlm/blob/master/http.c#L705

The use of `strlen()` here means only the first token is cleared since `pos`, and `dom` alias `buf` and are used to write nulls over the delimiters.

**Comment by fralken** [comment]
Hello, indeed you are right. It should be:
```
compat_memset_s(buf, header_bufsize, 0, header_bufsize);
```

**Comment by fralken** [comment]
Fixed by #106
