### ISSUE TITLE
Integration with osx keychain

### ISSUE THREAD

**Issue by droctothorpe** [versat/cntlm#116]
Hello. First of all, thank you for maintaining this wonderful project. cntlm is awesome.

It was recently blocked at my workplace because it stores (admittedly hashed) sensitive credentials in a text file. Would it be possible to integrate cntlm with osx keychain? How much of a lift do you think it would be?

Thanks!

**Comment by fralken** [comment]
Hello @droctothorpe have you checked whether you can use kerberos instead? With kerberos, cntlm gets credentials from the kerberos cache and it does not need them in the `cntlm.conf` file. You can start cntlm either with the command line param `-a gss` or by adding in the `cntlm.conf` the line `Auth GSS`.

**Comment by droctothorpe** [comment]
I will look into whether or not that's possible for our use case.  Thanks for the suggestion! Will close this issue for now until I confirm whether or not kerberos is an option for us. Much appreciated.
