### ISSUE TITLE
Encountering SIGSEGV after on successful request (statically linked, libpacparser, ppc64le)

### ISSUE THREAD

**Issue by mzpqnxow** [versat/cntlm#17]
Using the "feature" I submitted (static linking) in #16 I'm encountering a failure that seems to be associated with joining a thread after a request is complete. I'm entering this just for awareness and as a reminder for me to look further into it, I doubt you want to be supporting/debugging ppc64le & statically linked CNTLM- if you even have access to a ppc64le Linux machine :)

The request finishes successfully (the client gets the results) but then cntlm goes down with a SIGSEGV:

```
Connection                     => close
Content-Length                 => 93
Proxy-Authenticate             => NTLM
Sending headers (5)...
Body included. Length: 93
data_send: read 93 of 93 / 93 of 93 (errno = ok)
data_send: wrote 93 of 93
Body sent.
PROXY CLOSING CONNECTION
forward_request: palive=0, authok=0, ntlm=0, closed=1

Thread finished.
proxy_thread: request rc = 0xffffffffffffffff
Joined thread 70366707252944; rc: 0
```

In gdb, I'm seeing this, it appears to be a NULL pointer dereference, likely associated wioth the -1 return from `proxy_thread()`:

```
Thread finished.
proxy_thread: request rc = 0xffffffffffffffff
[LWP 16317 exited]
Joined thread 70367536021200; rc: 0

Thread 1 "cntlm" received signal SIGSEGV, Segmentation fault.
0x0000000010002b08 in main ()
(gdb) 
(gdb) x/4i $pc
=> 0x10002b08 <main+10568>:	lxvd2x  vs0,0,r9
   0x10002b0c <main+10572>:	stxvd2x vs0,r1,r10
   0x10002b10 <main+10576>:	bl      0x1013408c <select+8>
   0x10002b14 <main+10580>:	nop
(gdb) i r vs0 r9
vs0            {uint128 = 0x00000000000000000000000000000000, v2_double = {0x0, 0x0}, v4_float = {0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, 
  v16_int8 = {0x0 <repeats 16 times>}}
r9             0x0	0
(gdb) bt
#0  0x0000000010002b08 in main ()
(gdb) 
```

I'll look into this more as I get a chance. If you prefer, you can close the issue here and I can open it on my fork

**Comment by mzpqnxow** [comment]
For reference:

```
				ret = direct_request(thread_data, request);
#ifdef ENABLE_PACPARSER
			} else if (pacparser_initialized) {
				/* If PAC is available, use it to serve request. */
				ret = pac_forward_request(thread_data, request, pac_list);
			} else {
				/* Else use statically configured proxies. */
				ret = forward_request(thread_data, request, NULL);
			}
#else
			}
			else
				ret = forward_request(thread_data, request);
#endif

			if (debug)
				printf("proxy_thread: request rc = %p\n", (void *)ret);
#ifdef ENABLE_PACPARSER
		} while (ret != NULL && ret != (void *)-1 && ret != (void *)-2);
#else
		} while (ret != NULL && ret != (void *)-1);
#endif
        if (debug)
            printf("proxy_thread: request rc = %p\n", (void *)&request);
		free_rr_data(&request);
	/*
	 * If client asked for proxy keep-alive, loop unless the last server response
	 * requested (Proxy-)Connection: close.
	 */
#ifdef ENABLE_PACPARSER
	} while (keep_alive && ret != (void *)-1 && ret != (void *)-2 && !serialize);
#else
	} while (keep_alive && ret != (void *)-1 && !serialize);
#endif

	/*
	 * Add ourselves to the "threads to join" list.
	 */
	if (!serialize) {
        if (debug)
            printf("threads_mtx = %p\n", &threads_mtx);
		pthread_mutex_lock(&threads_mtx);
		pthread_t thread_id = pthread_self();
		threads_list = plist_add(threads_list, (unsigned long)thread_id, NULL);
		pthread_mutex_unlock(&threads_mtx);
	}

#ifdef ENABLE_PACPARSER
	plist_free(pac_list);
#endif
	free(thread_data);
	close(cd);

	return NULL;
}
```

Another important note- this was cross-compiled, so I'll need to try with a native toolchain on a ppc64le host to see if that may be part of the cause

**Comment by mzpqnxow** [comment]
It appears that this is associated with a linking mistake made by a human, specifically, me.

I would like to:

1. Reproduce this and see if a check can be added on whichever pointer that's getting dereferenced. Maybe I'm missing something with my quick glance, or maybe one of those functions is a cpp macro with a dereference in it, but I don't see anything being dereferenced. If I can find it' I'll wrap null check or assert around it
2. Make it more difficult for someone to make the same mistake I did when building

**Comment by jschwartzenberg** [comment]
Maybe I misunderstand something, but what happens when you compile with debug symbols and type `bt` in GDB after it segfaults?

**Comment by mzpqnxow** [comment]
I'm going to close this before it distracts or confuses anyone else :)

The issue goes away when the static library archive is produced properly anyway
