### ISSUE TITLE
Domain is cut off after 50 characters

### ISSUE THREAD

**Issue by florianbreieratbosch** [versat/cntlm#43]
Hi

We are facing a problem that we can't connect to a domain because it is cut off after 50 characters.
While analyzing we found that in main.c L791 the hostname is copied with the parameter MINIBUF_SIZE, although
our domain length is at 59 saved in the variable c some lines above. Thus the domain is cut off, which can be seen when switching -v for cntlm.
https://github.com/versat/cntlm/blob/80e3efadfdaed47c7eaa286719edc4fa89a8650d/main.c#L791
If I change the strlcpy function and replace MINIBUF_SIZE with the correct string length, debug mode prints out the correct domain but then gives me a STATUS_ACCESS_VIOLATION.

If I replace MINIBUF_SIZE by BUFSIZE at
https://github.com/versat/cntlm/blob/80e3efadfdaed47c7eaa286719edc4fa89a8650d/main.c#L617 
https://github.com/versat/cntlm/blob/80e3efadfdaed47c7eaa286719edc4fa89a8650d/main.c#L807
https://github.com/versat/cntlm/blob/80e3efadfdaed47c7eaa286719edc4fa89a8650d/main.c#L808

it works

As I don't understand the meaning of the MINIBUF_SIZE and why there is a restriction, I can't fix this issue.
Could you fix it or explain why there is a hard cut with 50 characters.
The issue happens with a socks connection between program and cntlm.

Thanks in advance
Florian

**Comment by versat** [comment]
I also think this was a simple and generic approach for these buffers, without thinking about real limits. 
A domain name, as far as I read in different places, can be up to 253 characters. So the buffer should have a size of at least 254 bytes. I would add another macro for domain name length and use it here.
