### ISSUE TITLE
build cntlm.exe on linux ubuntu OS

### ISSUE THREAD

**Issue by budtmo** [versat/cntlm#53]
**situation:**
I tried to build cntlm.exe under linux ubuntu OS. what I did:
- I have installed all needed packages to build cntlm
- I have copied all needed libraries of cygwin from windows OS to ubuntu OS (e.g. cyggcc_s-seh-1.dll, cygrunsrv.exe, cygstdc++-6.dll, cygwin1.dll)
- run `./configure && make && make win`
- I got an general error `strip: cntlm.exe: No such file`

**question:**
is there any way to build cntlm.exe under ubuntu OS? e.g. using [minGW-w64](https://www.mingw-w64.org/) on Linux Ubuntu OS

**Comment by fralken** [comment]
Do you need to cross-compile cntlm for Windows on a Linux machine?
If you simply run "make" it compiles the Linux version.
I guess you have to install Cygwin (maybe with wine) and try to build it from there. I don't know how it is practical, though.

**Comment by budtmo** [comment]
I want to build installer for all platforms (linux, osx, windows) on one OS, in my case on Linux Ubuntu, not on windows OS. I just copied cygwin libraries from windows OS to ubuntu OS just to make it work to build it on Ubuntu, because I saw that in Makefile, you need to copy those libraries. 

is there a way to use Ubuntu OS to build installer for all OS? @fralken

**Comment by fralken** [comment]
No it is not possible to cross compile on all platforms, you need specific include files and libraries, and set the compiler to target different binary formats.
The makefile is created to be multi platform, that is you can use it on Windows (on Cygwin), Linux and macOS. But it is not able to cross compile.

**Comment by budtmo** [comment]
ok, I will close the issue then. Thank you for the info @fralken
