### ISSUE TITLE
Are the build binaries avialable?

### ISSUE THREAD

**Issue by btsimonh** [versat/cntlm#71]
Hi All,

I see that the repo is being regularly built, including for OSX.
Are the binaries created stored anywhere?  I'd need windows, generic modern linux, and OSX.

I've been using px (python based), but with cntlm getting some great updates, including sspi, it becomes an attractive solution to our corporate networking woes... especially as px is now a folder full of deps, whereas cntlm still has minimal deps.

Simon

**Comment by versat** [comment]
Hi Simon,
sadly the binaries are not stored longer than the builds are retained currently (some days or weeks I think).
It would be great to create a release and retain these files for a long time. But I did not have time to set this up yet.
