### ISSUE TITLE
Detailed logging and adding custom headers

### ISSUE THREAD

**Issue by omerfsen** [versat/cntlm#72]
Hello is there a

1. Having detailed logging such as  suburl ?
2. Can we add custom headers to outgoing requests such as no-cache etc.

if not can we behave this issue as a Feature Request?

**Comment by jschwartzenberg** [comment]
> 1. Having detailed logging such as  suburl ?

There's a log of logging with `-v` but it's not really fine-tunable. If you need advanced logging capabilities, I guess the easiest would be to look through the code and implement specifically what you need. Maybe you could enhance the `-q` flag?


> 2. Can we add custom headers to outgoing requests such as no-cache etc.

There's the `-r` flag.

**Comment by omerfsen** [comment]
Can we define -r as a config stub ? Maybe something like

Header:  "Pragma: no-cache"
Header:  "Cache-Control: no-cache"

**Comment by omerfsen** [comment]
Header <headername: value>
Header substitution. See -r for details and remember, **no quoting.**

**Comment by omerfsen** [comment]
Header Pragma: no-cache
Header Cache-Control: no-cache

will do
